# Services used for development

version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=johndoe
      - POSTGRES_PASSWORD=randompassword
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  triggerdotdev:
    image: ghcr.io/triggerdotdev/trigger.dev:latest
    container_name: triggerdotdev
    restart: always
    ports:
      - 3030:3030
    depends_on:
      - postgres
    platform: linux/amd64 # This is required for Apple Silicon support
    env_file:
      - .env.local # loads env vars mainly to set the APP_ORIGIN
    environment:
      # The following environment variables are only used for development
      # and should not be used in production.
      # If you plan to self-host trigger.dev, you should follow the instructions here:
      # https://trigger.dev/docs/documentation/guides/self-hosting
      - LOGIN_ORIGIN=http://localhost:3030
      - PORT=3030
      - REMIX_APP_PORT=3030
      - MAGIC_LINK_SECRET=secret
      - SESSION_SECRET=secret
      - ENCRYPTION_KEY=ae13021afef0819c3a307ad487071c06
      - DATABASE_URL=postgresql://johndoe:randompassword@postgres:5432/triggerdev
      - DIRECT_URL=postgresql://johndoe:randompassword@postgres:5432/triggerdev
      - NODE_ENV=development
      - RUNTIME_PLATFORM=docker-compose
