import {cn} from '@repo/design-system/lib/utils'
import type {Metadata} from 'next'
import {Inter as FontSans} from 'next/font/google'

import {Providers} from './components/providers'
import {TailwindIndicator} from './components/tailwind-indicator'

import '@repo/design-system/reset.css'

export const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
})

export const metadata: Metadata = {
  title: 'Create Turborepo',
  description: 'Generated by create turbo',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}): JSX.Element {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          fontSans.variable,
        )}
      >
        <Providers>
          {children}
          <TailwindIndicator />
        </Providers>
      </body>
    </html>
  )
}
